Suppress acorn not installed warnings when listing projects
acorn-io/runtime pull request #2030
Opened 2023-08-07 22:56 UTC by keyallis

### Checklist
- [ ] The title of this PR would make a good line in Acorn's Release Note's Changelog
- [ ] The title of this PR ends with a link to the main issue being address in parentheses, like: `This is a title (#1216)`. [Here's an example](https://github.com/acorn-io/runtime/pull/1199)
- [ ] All relevant issues are referenced in the PR description. *NOTE: don't use [GitHub keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) that auto-close issues*
- [ ] Commits follow [contributing guidance](https://github.com/acorn-io/runtime/blob/main/CONTRIBUTING.md#commits)
- [ ] Automated tests added to cover the changes. If tests couldn't be added, an explanation is provided in the Verification and Testing section
- [ ] Changes to user-facing functionality, API, CLI, and upgrade impacts are clearly called out in PR description
- [ ] PR has at least two approvals before merging (or a reasonable exception, like it's just a docs change)

2023-08-07 23:55 UTC, cjellick approved these changes

2023-08-07 23:57 UTC, ibuildthecloud commented
What will happen if you can't contact a manager server?  That warning seems like it will be surpressed, no?

2023-08-08 00:16 UTC, cjellick commented
RIght on @ibuildthecloud.

So @keyallis - the error looks like this:
```WARN[0000] Could not list projects from [local kubeconfig]: failed to get API group resources: unable to retrieve the complete list of server APIs: api.acorn.io/v1: the server could not find the requested resource```

With "local kubeconfig" being the "key in that warning map. Maybe you can be a little more tactical with the warning you ignore? Only ignore the one for that key and only if the user did not pass in a kubeconfig param.

You should be able to force a bad connection to manager and get a warning for that, but not for the local kubeconfig.

I forced a bad connection by editing my acorn config (at `~/Library/Application\ Support/acorn/config.yaml`) and fudging the domain for manager. Note, I had to fudge ALL instances of that domain to get the warning.

2023-08-08 00:17 UTC, cjellick requested changes
see previous comment

2023-08-08 14:07 UTC, g-linville approved these changes

2023-08-11 16:26 UTC, merged